### ISSUE TITLE
Better way to get selected option

### ISSUE THREAD

**Issue by glen-84** [codrops/SelectInspiration#8]
From what I understand, it's possible for the `selected` property of an option to be set without the attribute being present. For this reason, I think that it would be better to use the following:

```js
var selectedOpt = this.el.options[this.el.selectedIndex];
```

Instead of the current:

```js
var selectedOpt = this.el.querySelector('option[selected]');
```

Would you accept a PR?

**Comment by botelho** [comment]
Sure! Thanks!
